name: Push
on: push

jobs:
  playwright:
    name: "${{ matrix.project }} - Playwright"
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.28.0-focal
      options: --ipc host --user 1001

    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit, chromium-mobile, webkit-mobile]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        node-version-file: ".nvmrc"
        cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run your tests
        run: npx playwright test --project=${{ matrix.project }}
